// GENERATED by scripts/gen-defillama-chain-aliases.ts from the committed
// docs/onchain-analytics/raw/defillama-chain-name-vocabularies-2026-08-11.json — do not edit by hand.
//
// DeFiLlama's LEGACY chain display name -> the CURRENT one. `/protocols` speaks the legacy
// vocabulary; `/v2/chains` — and therefore `registry.data.json`'s `vendors.defillama` column —
// speaks the current one. Without this map, matching by string misses 43 of 458 registry chains and
// `protocol.tvl` answers a confident `deployed: false, tvlUsd: 0` for chains a protocol is plainly
// on (measured: `aave` on `optimism`/`bsc`/`gnosis`/`zksync-era`, 2026-08-11).
//
// Derived from the vendor's own `chainId`/`gecko_id` identity columns, never from name similarity —
// see the generator for why `cmcId` is unusable and why `gecko_id` is only trusted when unique.

export const DEFILLAMA_CHAIN_ALIASES: ReadonlyMap<string, string> = new Map([
  ['Areon Network', 'Areum Network'],
  ['Binance', 'BSC'],
  ['Bitkub', 'KUB'],
  ['Camp', 'Camp Network'],
  ['Cosmos', 'CosmosHub'],
  ['EOS', 'Vaulta'],
  ['Echelon Chain', 'Echelon Initia'],
  ['Elrond', 'MultiversX'],
  ['Fuel', 'Fuel Ignition'],
  ['Goat', 'GOAT'],
  ['Gravity', 'Gravity by Galxe'],
  ['HydraDX', 'Hydration'],
  ['IDEX', 'XCHAIN'],
  ['Klaytn', 'Kaia'],
  ['Kucoin', 'KCC'],
  ['Mantra', 'MANTRA'],
  ['Map', 'MAP Protocol'],
  ['Milkomeda', 'Milkomeda C1'],
  ['Newton', 'AB'],
  ['OKExChain', 'OKTChain'],
  ['Oasis', 'Oasis Emerald'],
  ['Op_Bnb', 'opBNB'],
  ['Optimism', 'OP Mainnet'],
  ['Orai', 'Oraichain'],
  ['Persistence', 'Persistence One'],
  ['Proton', 'XPR Network'],
  ['Pulse', 'PulseChain'],
  ['RSK', 'Rootstock'],
  ['Reya Network', 'ReyaChain'],
  ['Ripple', 'XRPL'],
  ['SXnetwork', 'SX Network'],
  ['Sapphire', 'Oasis Sapphire'],
  ['Story', 'Data Network'],
  ['Terra', 'Terra Classic'],
  ['Thorchain', 'THORChain'],
  ['TomoChain', 'Viction'],
  ['UNIT0', 'Unit Zero'],
  ['Umee', 'UX'],
  ['WEMIX', 'WEMIX3.0'],
  ['xDai', 'Gnosis'],
  ['zkLink', 'zkLink Nova'],
  ['zkSync Era', 'ZKsync Era'],
]);
