import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { createNansenAdapter } from '../src/adapters/nansen/index.js';
import {
  NANSEN_CHAIN_COVERAGE,
  NANSEN_EXHAUSTIVE_LABELS_CHAINS,
} from '../src/adapters/nansen/chain-coverage.js';
import { loadChainRegistry } from '../src/chain/registry.js';

/**
 * Task 006-9 (R-58) — Nansen coverage derived from the COMMITTED spec, per capability, with a
 * composite capability covered only by the INTERSECTION of its sub-calls.
 */
const CHAINS = loadChainRegistry();
const adapter = createNansenAdapter();
const supports = (slug: string, capability: string): boolean =>
  adapter.chainSupport!(CHAINS.resolve(slug), capability);

describe('composite capability = intersection, never union (the DF-1 failure class)', () => {
  // These seven are covered by `/tgm/*` but NOT by `/smart-money/netflow`. A union would list them
  // for `smart-money.flows`, where the first sub-call succeeds, the second is refused, and the
  // credits for the first are already gone.
  const HALF_SUCCEEDING = ['injective', 'mantra', 'near', 'starknet', 'sui', 'ton', 'tron'];

  it.each(HALF_SUCCEEDING)('%s is NOT covered for smart-money.flows', (slug) => {
    expect(supports(slug, 'smart-money.flows')).toBe(false);
  });

  it.each(HALF_SUCCEEDING)(
    '%s IS covered for token.risk (per-capability, not per-adapter)',
    (slug) => {
      expect(supports(slug, 'token.risk')).toBe(true);
    },
  );

  it('smart-money.flows is a strict subset of token.risk', () => {
    const flows = NANSEN_CHAIN_COVERAGE['smart-money.flows']!;
    const risk = NANSEN_CHAIN_COVERAGE['token.risk']!;
    expect(flows.length).toBeLessThan(risk.length);
  });
});

describe('the generated module is faithful to the spec', () => {
  it("excludes 'all' — a query modifier, not a chain", () => {
    for (const chains of Object.values(NANSEN_CHAIN_COVERAGE)) {
      expect(chains).not.toContain('all');
    }
    expect(NANSEN_EXHAUSTIVE_LABELS_CHAINS).not.toContain('all');
  });

  it('is marked generated so nobody hand-edits it', () => {
    const src = readFileSync('src/adapters/nansen/chain-coverage.ts', 'utf8');
    expect(src).toContain('GENERATED by scripts/gen-nansen-coverage.ts');
    expect(src).toContain('do not edit by hand');
  });

  it('keeps the exhaustive labels tier narrower than the default tier', () => {
    // It matters BEFORE the 100cr escalation: refusing early is the whole point.
    expect(NANSEN_EXHAUSTIVE_LABELS_CHAINS.length).toBeLessThan(
      NANSEN_CHAIN_COVERAGE['entity.labels']!.length,
    );
  });
});

describe('vendor tokens vs our slugs', () => {
  it('uses the VENDOR token, not our slug (bsc→bnb, op-mainnet→optimism)', () => {
    expect(CHAINS.resolve('bsc').vendors['nansen']).toBe('bnb');
    expect(CHAINS.resolve('op-mainnet').vendors['nansen']).toBe('optimism');
    expect(supports('bsc', 'token.risk')).toBe(true);
    expect(supports('op-mainnet', 'token.risk')).toBe(true);
  });

  it('a chain with no vendor token is not covered, whatever the capability', () => {
    const unmapped = CHAINS.list().find((c) => c.vendors['nansen'] == null)!;
    for (const capability of Object.keys(NANSEN_CHAIN_COVERAGE)) {
      expect(adapter.chainSupport!(unmapped, capability), `${unmapped.slug}/${capability}`).toBe(
        false,
      );
    }
  });

  it('an unknown capability covers nothing (fail-closed)', () => {
    expect(supports('ethereum', 'some.capability.we.never.declared')).toBe(false);
  });
});

describe('M2 regression — the original pair still works everywhere', () => {
  it.each(['ethereum', 'solana'])('%s stays covered by all three paid capabilities', (slug) => {
    expect(supports(slug, 'smart-money.flows')).toBe(true);
    expect(supports(slug, 'entity.labels')).toBe(true);
    expect(supports(slug, 'token.risk')).toBe(true);
  });
});
