/**
 * Generates `src/adapters/blockscout/chains.ts` from the committed, provenance-pinned evidence
 * (`docs/onchain-analytics/raw/blockscout-chains-2026-07-28.json`, a live keyless
 * `GET https://mcp.blockscout.com/v1/get_chains_list`).
 *
 * TASK-008 R-77. Same shape as `gen-defillama-dex-chains.ts` and for the same reason: coverage that
 * is asserted rather than derived drifts silently, and the drift is invisible in review because a
 * hardcoded list looks identical whether it is right or wrong.
 *
 * **The emitted key is the numeric `chain_id`, and that choice is load-bearing.** The vendor also
 * ships an `ecosystem` field that reads like a chain family and is not one: `ecosystem: "Solana"` is
 * Neon (an EVM chain, id 245022934) and `ecosystem: "Bitcoin/BCH"` is Rootstock (an EVM sidechain,
 * id 30). Every one of the 100 ids is numeric — the whole list is EVM. Keying coverage on
 * `ecosystem` would advertise `svm`/`utxo` support that does not exist, which is the H-1 defect
 * class from TASK-006 and exactly what `dex.volume.history` was built to avoid.
 *
 * Testnets are dropped: 47 of the 100 rows carry `is_testnet: true`, and a testnet answering a
 * production question is worse than no answer.
 *
 * Run from `packages/core`:
 *   pnpm exec tsx scripts/gen-blockscout-chains.ts
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const EVIDENCE = '../../docs/onchain-analytics/raw/blockscout-chains-2026-07-28.json';
const OUT = 'src/adapters/blockscout/chains.ts';

/**
 * A floor, not a fit. The recorded evidence holds 53 mainnets; this only has to be low enough never
 * to fire on normal vendor churn and high enough to catch a truncated or half-written response,
 * which is the failure this guard exists for — silently emitting a nearly-empty list would narrow
 * coverage to nothing and look like a clean run.
 */
const MIN_PLAUSIBLE_MAINNETS = 25;

interface EvidenceChain {
  name?: unknown;
  chain_id?: unknown;
  is_testnet?: unknown;
  ecosystem?: unknown;
}

interface Evidence {
  data?: unknown;
}

/**
 * Refuse rather than coerce. A `chain_id` that is not a plain non-negative integer string means the
 * vendor changed its identifier scheme, and guessing what it now means would put a wrong id into
 * request URLs — i.e. we would query some other chain and label the answer with this one. The same
 * "refuse, don't guess" rule the Solana lamports path follows (WI-8).
 */
function parseChainId(value: unknown, name: string): number {
  if (typeof value !== 'string' || !/^(0|[1-9][0-9]*)$/.test(value)) {
    throw new Error(
      `gen-blockscout-chains: chain "${name}" has a non-numeric chain_id ` +
        `(${JSON.stringify(value)}). The vendor's identifier scheme changed — this generator ` +
        'refuses to guess, because a wrong id silently queries a different chain.',
    );
  }
  const id = Number(value);
  if (!Number.isSafeInteger(id)) {
    throw new Error(
      `gen-blockscout-chains: chain "${name}" has a chain_id outside the safe range.`,
    );
  }
  return id;
}

export function generateBlockscoutChains(evidencePath = EVIDENCE, outPath = OUT): number[] {
  const evidence = JSON.parse(readFileSync(evidencePath, 'utf8')) as Evidence;
  const rows = evidence.data;
  if (!Array.isArray(rows)) {
    throw new Error('gen-blockscout-chains: evidence has no `data` array — refusing to write.');
  }

  const mainnets: number[] = [];
  for (const row of rows as EvidenceChain[]) {
    const name = typeof row.name === 'string' ? row.name : '<unnamed>';
    // Explicitly `!== true`, not `!row.is_testnet`: a missing flag on a new row must be treated as
    // "unknown", and an unknown testnet flag is the case where being wrong is expensive. A vendor
    // that stops sending the field would otherwise silently promote 47 testnets into coverage.
    if (row.is_testnet !== false) continue;
    mainnets.push(parseChainId(row.chain_id, name));
  }

  if (mainnets.length < MIN_PLAUSIBLE_MAINNETS) {
    throw new Error(
      `gen-blockscout-chains: only ${mainnets.length} mainnets in the evidence ` +
        `(< ${MIN_PLAUSIBLE_MAINNETS}). Refusing to write a suspiciously narrow coverage list; ` +
        're-record the evidence and check the response before re-running.',
    );
  }

  const sorted = [...new Set(mainnets)].sort((a, b) => a - b);

  const body = `// GENERATED by scripts/gen-blockscout-chains.ts from the committed
// docs/onchain-analytics/raw/blockscout-chains-2026-07-28.json — do not edit by hand.
//
// The numeric EVM chain ids Blockscout serves on its MAINNET explorers, taken from the vendor's own
// get_chains_list (100 rows: ${rows.length - sorted.length} testnets dropped, ${sorted.length} kept).
//
// Keyed on chain_id, never on the vendor's \`ecosystem\` field — that field looks like a chain family
// and is not one (\`ecosystem: "Solana"\` is Neon, an EVM chain; \`"Bitcoin/BCH"\` is Rootstock, an EVM
// sidechain). Our registry maps these ids through \`caip2 === \\\`eip155:\\\${id}\\\`\`.

export const BLOCKSCOUT_CHAIN_IDS: readonly number[] = [
${sorted.map((id) => `  ${id},`).join('\n')}
];
`;

  writeFileSync(outPath, body, 'utf8');
  return sorted;
}

const invokedDirectly = process.argv[1]?.endsWith('gen-blockscout-chains.ts') ?? false;
if (invokedDirectly) {
  const emitted = generateBlockscoutChains();
  process.stderr.write(`gen-blockscout-chains: wrote ${emitted.length} mainnet chain ids\n`);

  // Hand the artifact to the repo's own formatter instead of hand-matching its output.
  // Non-obvious and worth stating: this file is a list of SHORT numbers, and prettier packs those
  // several to a line rather than one-per-line the way it leaves the longer strings in
  // `dex-chains.ts`. Emitting a shape "that looks formatted" would therefore drift from
  // `pnpm format:check` on the very first run — a generated file that fails the repo's own gate is
  // a generator defect, not a formatting preference. Kept OUT of `generateBlockscoutChains()` so
  // the exported function stays hermetic and fast for tests.
  execFileSync('pnpm', ['exec', 'prettier', '--write', OUT], { stdio: 'ignore' });

  // Diagnostic, never a gate: how much of the vendor's coverage our registry can actually name.
  // An id we cannot map is not an error — it is a chain we do not model yet — but the count going
  // to zero would mean the mapping key broke, and that must be visible rather than inferred.
  const registry = JSON.parse(readFileSync('src/chain/registry.data.json', 'utf8')) as {
    chains?: Array<{ caip2?: string }>;
  };
  const known = new Set(
    (registry.chains ?? [])
      .map((row) => /^eip155:(\d+)$/.exec(row.caip2 ?? '')?.[1])
      .filter((id): id is string => id !== undefined)
      .map(Number),
  );
  const mapped = emitted.filter((id) => known.has(id));
  process.stderr.write(
    `gen-blockscout-chains: ${mapped.length}/${emitted.length} map to a registry chain ` +
      `(${emitted.length - mapped.length} unmodelled)\n`,
  );
}
