/**
 * `gen-defillama-dex-chains` — emits the DeFiLlama DEX-volume chain list from committed live
 * evidence (TASK-007 task 007-2, R-63).
 *
 * A dev script, same contract as `sync-chain-registry.ts` and `gen-nansen-coverage.ts`: nothing
 * under `src/` imports it, it reads a committed raw artifact and writes a committed `.ts` module,
 * and the review happens on the git diff.
 *
 * **Why this list cannot be `vendors.defillama`.** That registry column was populated from the
 * vendor's TVL catalog (`/v2/chains`) and is non-null for all 458 registry rows. The vendor's
 * DEX-volume dataset is a different and much smaller set — 287 chains in the recorded `allChains`,
 * of which 274 exist in our registry. Reusing the TVL predicate would advertise
 * `dex.volume.history` on 184 chains that have no such data: the defect class TASK-006's review
 * recorded as H-1 (coverage widened, transport not).
 *
 * **Why a build artifact and not a startup fetch** — the three reasons the chain registry itself is
 * one (data-model.md §4.2.1): the offline-run gate ("a full test run makes zero network calls"), CI
 * determinism (a test whose outcome depends on what a vendor served today is not a test), and
 * reviewability (a change to the covered set is a diff a human reads). The stated consequence is the
 * same too: freshness is the OPERATOR's job. A chain that appears at the vendor becomes available
 * after this script is run and the snapshot committed — never automatically.
 *
 * Usage: pnpm --filter @onchain-intel/core exec tsx scripts/gen-defillama-dex-chains.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

const EVIDENCE = '../../docs/onchain-analytics/raw/defillama-dexs-allchains-2026-07-27.json';
const OUT = 'src/adapters/defillama/dex-chains.ts';

/**
 * Floor on a plausible list size. The vendor served 287; anything under 50 means the response shape
 * changed, the field moved, or the recording is truncated — and the failure mode of accepting it
 * silently is the worst one available: an EMPTY or near-empty list makes the capability quietly
 * uncovered everywhere, which looks exactly like "the feature was never built".
 */
const MIN_PLAUSIBLE_CHAINS = 50;

interface Evidence {
  allChains?: unknown;
}

/**
 * Guards a VENDOR-supplied string before it is interpolated into a TypeScript source literal — the
 * same doctrine as `gen-nansen-coverage.ts`'s `safeToken`, with one deliberate difference: SPACE is
 * allowed, because real vendor names contain it (`OP Mainnet`, `Hyperliquid L1`).
 *
 * The emit below builds `'<value>'` by hand, so a value containing a quote, a backslash or a newline
 * would close the literal early and inject arbitrary source into a COMMITTED `src/` module.
 * Escaping would make that safe and silent; refusing makes it safe and VISIBLE — a chain name
 * outside this class is a vendor-drift signal that deserves a human, not a quiet encode.
 */
function safeName(value: string): string {
  if (!/^[A-Za-z0-9][A-Za-z0-9 ._-]*$/.test(value)) {
    throw new Error(
      `gen-defillama-dex-chains: refusing to emit an unexpected vendor chain name ${JSON.stringify(value)} — ` +
        'expected /^[A-Za-z0-9][A-Za-z0-9 ._-]*$/. Inspect the evidence before widening this guard.',
    );
  }
  return value;
}

export function generateDefillamaDexChains(evidencePath = EVIDENCE, outPath = OUT): string[] {
  const evidence = JSON.parse(readFileSync(evidencePath, 'utf8')) as Evidence;
  const raw = evidence.allChains;
  if (!Array.isArray(raw)) {
    throw new Error(`gen-defillama-dex-chains: evidence has no 'allChains' array`);
  }
  const names = raw.filter((value): value is string => typeof value === 'string');
  if (names.length !== raw.length) {
    throw new Error(
      `gen-defillama-dex-chains: 'allChains' holds ${raw.length - names.length} non-string entries`,
    );
  }
  if (names.length < MIN_PLAUSIBLE_CHAINS) {
    throw new Error(
      `gen-defillama-dex-chains: only ${names.length} chains in the evidence (< ${MIN_PLAUSIBLE_CHAINS}). ` +
        'Refusing to emit a near-empty coverage list — an empty list silently uncovers the capability everywhere.',
    );
  }

  // Sorted + de-duplicated so a re-run on the same input is byte-identical (the generator must not
  // produce a diff that is only reordering).
  const sorted = [...new Set(names.map(safeName))].sort();

  const body = `// GENERATED by scripts/gen-defillama-dex-chains.ts from the committed
// docs/onchain-analytics/raw/defillama-dexs-allchains-2026-07-27.json — do not edit by hand.
//
// The vendor's OWN list of chains its DEX-volume dataset covers (\`allChains\` of a live keyless
// /overview/dexs response). This is NOT \`vendors.defillama\` in the chain registry: that column came
// from the vendor's TVL catalog and is non-null for all 458 registry rows, while this set is 287.
// Using the TVL predicate for \`dex.volume.history\` would advertise the capability on 184 chains
// that have no such data (TASK-007 R-63).
//
// Values are DEFILLAMA's own display names, not our slugs; \`registry.data.json\`'s
// \`vendors.defillama\` column maps between them.

export const DEFILLAMA_DEX_CHAINS: readonly string[] = [
${sorted.map((name) => `  '${name}',`).join('\n')}
];
`;

  writeFileSync(outPath, body, 'utf8');
  return sorted;
}

const invokedDirectly = process.argv[1]?.endsWith('gen-defillama-dex-chains.ts') ?? false;
if (invokedDirectly) {
  const emitted = generateDefillamaDexChains();
  process.stdout.write(`DEFILLAMA_DEX_CHAINS -> ${emitted.length} vendor chain names\n`);

  // Report the overlap with the chain registry rather than leaving it implicit. A vendor chain we
  // have no registry row for is covered by nothing — an honest gap, but one an operator should see
  // rather than discover later from a missing answer.
  const registry = JSON.parse(readFileSync('src/chain/registry.data.json', 'utf8')) as {
    chains: { slug: string; vendors: Record<string, string | null> }[];
  };
  const known = new Set(
    registry.chains
      .map((chain) => chain.vendors['defillama'])
      .filter((name): name is string => name != null),
  );
  const unmapped = emitted.filter((name) => !known.has(name));
  process.stdout.write(
    `covered in our registry: ${emitted.length - unmapped.length} of ${emitted.length}\n`,
  );
  if (unmapped.length > 0) {
    process.stdout.write(
      `NOT in the chain registry (${unmapped.length}): ${unmapped.join(', ')}\n`,
    );
  }
}
