/**
 * Renders the tool inventory as a committed JSON artifact, for readers that cannot import
 * TypeScript (TASK-011, R-114).
 *
 * **Why an artifact rather than "just import the registry".** Two consumers cannot:
 * `scripts/smoke-dist.mjs` is deliberately dependency-free — it speaks raw JSON-RPC and imports
 * neither the SDK nor any TypeScript, which is what lets it test the shipped `dist/` without
 * dragging the build into its own dependencies — and `eval/*.mjs` are plain ESM data modules whose
 * own contract says importing them must never start a server. Both can, however, read a file.
 *
 * **Identity only, never schemas.** `name`, `title` and the served `capability` — the facts a
 * non-TypeScript reader actually needs. Descriptions are deliberately absent: nothing reads them
 * here, and `test/fixtures/tools-list.snapshot.json` already freezes them. A second copy of the
 * same text is exactly the duplication this task exists to remove.
 *
 * **This file is not imported from `src/`.** `resolveJsonModule` is enabled only in
 * `@onchain-intel/core`, and `with { type: 'json' }` is pinned as flaky under this
 * TypeScript/NodeNext combination; more importantly `src/` already has the registry itself, so an
 * import here would be a second path to the same fact.
 *
 * Run: pnpm --filter @onchain-intel/mcp-server gen:tools
 */

import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { toolSpecs } from '../src/tools/tool-specs.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));

/** The committed artifact. Package root, not `src/` — it is data for outside readers, not source. */
export const INVENTORY_PATH = path.resolve(HERE, '../tool-inventory.json');

/** The command a failing gate must print. */
export const GENERATE_COMMAND = 'pnpm --filter @onchain-intel/mcp-server gen:tools';

export interface ToolInventoryEntry {
  readonly name: string;
  readonly title: string;
  /** `null` for the tools that serve no capability — written, not omitted. Also `null` for a tool
   * serving SEVERAL, which names them in `servedCapabilities` (T-013 task 013-7). */
  readonly capability: string | null;
  /**
   * Present only on a tool serving more than one capability (T-013 task 013-7).
   *
   * **It has to reach the ARTIFACT, not just the spec**, because `eval/capabilities.mjs` is `.mjs`
   * and reads nothing else — it cannot import `tool-specs.ts`. A `servedCapabilities` that stopped
   * at `ToolSpec` would leave that reader mapping the new tool to no capability at all, silently.
   */
  readonly servedCapabilities?: readonly string[];
}

export interface ToolInventory {
  readonly $comment: string;
  /** In publication order, matching `toolSpecs` and therefore `tools/list`. */
  readonly tools: readonly ToolInventoryEntry[];
}

const COMMENT =
  `GENERATED by scripts/gen-tool-inventory.ts (TASK-011 R-114) from src/tools/tool-specs.ts — ` +
  `do not hand-edit. Order matches tools/list. Regenerate with: ${GENERATE_COMMAND}`;

/** Builds the artifact from the registry. Pure: the test calls it without writing anything. */
export function buildToolInventory(): ToolInventory {
  return {
    $comment: COMMENT,
    tools: toolSpecs.map((spec) => ({
      name: spec.name,
      title: spec.title,
      capability: spec.capability,
      // Conditional, so the 13 single-capability entries keep exactly three keys and the artifact
      // bytes do not move until a multi-capability tool is actually registered (013-8).
      ...(spec.servedCapabilities !== undefined
        ? { servedCapabilities: [...spec.servedCapabilities] }
        : {}),
    })),
  };
}

/** The exact bytes of the artifact, so "in sync" is a string comparison and not a deep-equal. */
export function serializeToolInventory(inventory: ToolInventory): string {
  return `${JSON.stringify(inventory, null, 2)}\n`;
}

/**
 * Writes the artifact and returns it.
 *
 * Both parameters are injectable so the test can exercise this for real rather than around it:
 * `outPath` lets it write to a tmpdir, and `inventory` lets it hand in an empty one and watch the
 * refusal below actually fire. A guard that cannot be reached from a test is a guard nobody has
 * ever seen work.
 */
export function generateToolInventory(
  outPath: string = INVENTORY_PATH,
  inventory: ToolInventory = buildToolInventory(),
): ToolInventory {
  if (inventory.tools.length === 0) {
    // A generator that happily writes an empty inventory would turn a broken import into a green
    // artifact, and every downstream reader would then agree that this server has no tools.
    throw new Error('gen-tool-inventory: the registry is empty — refusing to write.');
  }
  writeFileSync(outPath, serializeToolInventory(inventory), 'utf8');
  return inventory;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const written = generateToolInventory();
  console.log(`gen-tool-inventory: wrote ${written.tools.length} tools to ${INVENTORY_PATH}`);
}
