/**
 * DDL for the cache database (`${DATA_DIR}/cache.sqlite3`, ARCHITECTURE.md §3.2/§4.2), applied via
 * `db.exec(CACHE_DDL)` on every `SqliteCacheStore` open (idempotent — `IF NOT EXISTS` guards). This
 * is declarative data, not logic (task 003-3 note) — the same string ships unchanged from Phase 1.
 *
 * DB-SCHEMA-CONCEPT §1 portable-type discipline, applied to this NEW context (a cache, not the
 * analytics snapshot schema n8n writes independently):
 * - Only TEXT / INTEGER / REAL columns — no engine-specific column types anywhere in this schema.
 * - All time values are epoch-ms UTC INTEGER columns (`created_at`, `expires_at`) — never a native
 *   date/time column type and never a SQL date/time function in application logic.
 * - `cache_entries.id` is an app-generated ULID (TEXT) — the app always supplies it explicitly on
 *   insert; nothing here relies on the engine's own row-numbering feature, so IDs stay globally
 *   unique and portable across any future engine swap.
 * - `value_json` is the canonical result, JSON-serialized to TEXT — parsed app-side only, never
 *   queried with an engine-specific JSON operator.
 *
 * Write semantics: `cache_entries` is a recomputable projection, not an append-only observation log
 * (DB-SCHEMA-CONCEPT §1.5's "aggregates" branch, applied here) — `SqliteCacheStore.set()` uses
 * `INSERT ... ON CONFLICT (provider, capability, args_hash) DO UPDATE`, never a
 * conflict-do-nothing insert, so a re-fetched value always overwrites a stale row instead of
 * silently pinning it in place.
 *
 * `providers` is upserted from ALL 9 `adapterRegistrations` (including `pg-history`) BEFORE any
 * `cache_entries` row can reference it — `cache_entries.provider` is a foreign key into this table,
 * enforced only because `SqliteCacheStore` issues the explicit pragma below on every connection
 * open (DB-SCHEMA-CONCEPT §1.6 — the engine does not enforce a reference column by default).
 *
 * M2 (TASK-005, task 005-2, R-34/R-35) landed the `usage` table this forward-compat note reserved
 * a place for: `usage(provider FK, day, credits_used, updated_at)`, referencing this SAME
 * `providers` registry as its own foreign key — added below as a plain `CREATE TABLE IF NOT
 * EXISTS`, no migration of `providers`/`cache_entries` required, exactly as this note originally
 * promised. Unlike `cache_entries` above (an overwrite-upsert), `usage.credits_used` is an
 * ADDITIVE counter: `SqliteBudgetStore`'s (`budget-store.ts`) write is `INSERT ... VALUES (…,
 * MAX(0, @delta), …) ON CONFLICT (provider, day) DO UPDATE SET credits_used = MAX(0, credits_used
 * + @delta), ...` — never a plain overwrite. Note the DO UPDATE branch binds **`@delta`, NOT
 * `excluded.credits_used`** (cycle-2 review L-3 corrected this note, which still described the
 * abandoned form): in SQLite `excluded.credits_used` IS the VALUES expression, so once VALUES is
 * clamped, referencing `excluded` would make the update branch unable to SUBTRACT — silently
 * breaking every reconciliation refund. Do not "restore consistency" by switching it back. It accumulates signed deltas (pre-call reservation, then post-call
 * reconciliation — both `budget-store.ts`), clamped at 0 via `MAX(0, …)` so a defensive/edge-case
 * negative delta can never drive the counter below its documented never-negative invariant. `day`
 * is an epoch-ms UTC day-bucket start (`dayBucketMs()`, `cache/day-bucket.ts`) — DB-SCHEMA-CONCEPT
 * §1.2's "no string local dates" canon applied literally here too, despite ADR-001 D6 calling the
 * column "day". `credits_used` is a plain `INTEGER`, not the `value_raw TEXT` pattern
 * `cache_entries`/`Snapshot` use elsewhere — a documented, small-in-range internal engine counter,
 * not an arbitrary-precision canonical observation (R-34).
 */
export const CACHE_DDL = `
CREATE TABLE IF NOT EXISTS providers (
  id    TEXT PRIMARY KEY,   -- adapter.id, e.g. 'coingecko' | 'rpc-evm' | ... (ARCHITECTURE.md §3.2)
  kind  TEXT NOT NULL,      -- 'free' | 'paid' — informational only, reflects D4 priority
  notes TEXT
);

CREATE TABLE IF NOT EXISTS cache_entries (
  id          TEXT PRIMARY KEY,              -- ULID, generated by the app (DB-SCHEMA-CONCEPT §1.3)
  provider    TEXT NOT NULL REFERENCES providers(id),
  capability  TEXT NOT NULL,
  args_hash   TEXT NOT NULL,                 -- sha256(hex) of normalized args — NEVER secrets (§7.2)
  value_json  TEXT NOT NULL,                 -- canonical result, JSON as TEXT (DB-SCHEMA-CONCEPT §1.4)
  created_at  INTEGER NOT NULL,              -- epoch-ms UTC
  expires_at  INTEGER NOT NULL,              -- epoch-ms UTC = created_at + TTL(capability)
  UNIQUE (provider, capability, args_hash)
);

CREATE INDEX IF NOT EXISTS idx_cache_entries_expiry ON cache_entries (expires_at);

CREATE TABLE IF NOT EXISTS usage (
  provider     TEXT NOT NULL REFERENCES providers(id),
  day          INTEGER NOT NULL,           -- epoch-ms UTC bucket start: floor(ts/86400000)*86400000
  credits_used INTEGER NOT NULL DEFAULT 0, -- ADDITIVE counter, never overwritten (see note above)
  updated_at   INTEGER NOT NULL,           -- epoch-ms UTC of the last write — observability only
  PRIMARY KEY (provider, day),
  -- Enforced at the ENGINE level, not just by the MAX(0, …) in both upsert branches (adversarial
  -- cycle 1): a negative credits_used would read as free headroom in checkAndReserve and silently
  -- widen the budget. The never-negative rule was documented here but previously enforced by
  -- nothing. Portable across SQLite and Postgres (DB-SCHEMA-CONCEPT §1) — a plain column CHECK.
  CHECK (credits_used >= 0)
);
`;
