/**
 * DDL for the cache database (`${DATA_DIR}/cache.sqlite3`, ARCHITECTURE.md §3.2/§4.2), applied via
 * `db.exec(CACHE_DDL)` on every `SqliteCacheStore` open (idempotent — `IF NOT EXISTS` guards). This
 * is declarative data, not logic (task 003-3 note) — the same string ships unchanged from Phase 1.
 *
 * DB-SCHEMA-CONCEPT §1 portable-type discipline, applied to this NEW context (a cache, not the
 * analytics snapshot schema n8n writes independently):
 * - Only TEXT / INTEGER / REAL columns — no engine-specific column types anywhere in this schema.
 * - All time values are epoch-ms UTC INTEGER columns (`created_at`, `expires_at`) — never a native
 *   date/time column type and never a SQL date/time function in application logic.
 * - `cache_entries.id` is an app-generated ULID (TEXT) — the app always supplies it explicitly on
 *   insert; nothing here relies on the engine's own row-numbering feature, so IDs stay globally
 *   unique and portable across any future engine swap.
 * - `value_json` is the canonical result, JSON-serialized to TEXT — parsed app-side only, never
 *   queried with an engine-specific JSON operator.
 *
 * Write semantics: `cache_entries` is a recomputable projection, not an append-only observation log
 * (DB-SCHEMA-CONCEPT §1.5's "aggregates" branch, applied here) — `SqliteCacheStore.set()` uses
 * `INSERT ... ON CONFLICT (provider, capability, args_hash) DO UPDATE`, never a
 * conflict-do-nothing insert, so a re-fetched value always overwrites a stale row instead of
 * silently pinning it in place.
 *
 * `providers` is upserted from ALL 9 `adapterRegistrations` (including `pg-history`) BEFORE any
 * `cache_entries` row can reference it — `cache_entries.provider` is a foreign key into this table,
 * enforced only because `SqliteCacheStore` issues the explicit pragma below on every connection
 * open (DB-SCHEMA-CONCEPT §1.6 — the engine does not enforce a reference column by default).
 *
 * M2 (TASK-005, task 005-2, R-34/R-35) landed the `usage` table this forward-compat note reserved
 * a place for: `usage(provider FK, day, credits_used, updated_at)`, referencing this SAME
 * `providers` registry as its own foreign key — added below as a plain `CREATE TABLE IF NOT
 * EXISTS`, no migration of `providers`/`cache_entries` required, exactly as this note originally
 * promised. Unlike `cache_entries` above (an overwrite-upsert), `usage.credits_used` is an
 * ADDITIVE counter: `SqliteBudgetStore`'s (`budget-store.ts`) write is `INSERT ... VALUES (…,
 * MAX(0, @delta), …) ON CONFLICT (provider, day) DO UPDATE SET credits_used = MAX(0, credits_used
 * + @delta), ...` — never a plain overwrite. Note the DO UPDATE branch binds **`@delta`, NOT
 * `excluded.credits_used`** (cycle-2 review L-3 corrected this note, which still described the
 * abandoned form): in SQLite `excluded.credits_used` IS the VALUES expression, so once VALUES is
 * clamped, referencing `excluded` would make the update branch unable to SUBTRACT — silently
 * breaking every reconciliation refund. Do not "restore consistency" by switching it back. It accumulates signed deltas (pre-call reservation, then post-call
 * reconciliation — both `budget-store.ts`), clamped at 0 via `MAX(0, …)` so a defensive/edge-case
 * negative delta can never drive the counter below its documented never-negative invariant. `day`
 * is an epoch-ms UTC day-bucket start (`dayBucketMs()`, `cache/day-bucket.ts`) — DB-SCHEMA-CONCEPT
 * §1.2's "no string local dates" canon applied literally here too, despite ADR-001 D6 calling the
 * column "day". `credits_used` is a plain `INTEGER`, not the `value_raw TEXT` pattern
 * `cache_entries`/`Snapshot` use elsewhere — a documented, small-in-range internal engine counter,
 * not an arbitrary-precision canonical observation (R-34).
 */
export const CACHE_DDL = `
CREATE TABLE IF NOT EXISTS providers (
  id    TEXT PRIMARY KEY,   -- adapter.id, e.g. 'coingecko' | 'rpc-evm' | ... (ARCHITECTURE.md §3.2)
  kind  TEXT NOT NULL,      -- 'free' | 'paid' — informational only, reflects D4 priority
  notes TEXT
);

CREATE TABLE IF NOT EXISTS cache_entries (
  id          TEXT PRIMARY KEY,              -- ULID, generated by the app (DB-SCHEMA-CONCEPT §1.3)
  provider    TEXT NOT NULL REFERENCES providers(id),
  capability  TEXT NOT NULL,
  args_hash   TEXT NOT NULL,                 -- sha256(hex) of normalized args — NEVER secrets (§7.2)
  value_json  TEXT NOT NULL,                 -- canonical result, JSON as TEXT (DB-SCHEMA-CONCEPT §1.4)
  created_at  INTEGER NOT NULL,              -- epoch-ms UTC
  expires_at  INTEGER NOT NULL,              -- epoch-ms UTC = created_at + TTL(capability)
  UNIQUE (provider, capability, args_hash)
);

CREATE INDEX IF NOT EXISTS idx_cache_entries_expiry ON cache_entries (expires_at);

CREATE TABLE IF NOT EXISTS usage (
  provider     TEXT NOT NULL REFERENCES providers(id),
  day          INTEGER NOT NULL,           -- epoch-ms UTC bucket start: floor(ts/86400000)*86400000
  credits_used INTEGER NOT NULL DEFAULT 0, -- ADDITIVE counter, never overwritten (see note above)
  updated_at   INTEGER NOT NULL,           -- epoch-ms UTC of the last write — observability only
  PRIMARY KEY (provider, day),
  -- Enforced at the ENGINE level, not just by the MAX(0, …) in both upsert branches (adversarial
  -- cycle 1): a negative credits_used would read as free headroom in checkAndReserve and silently
  -- widen the budget. The never-negative rule was documented here but previously enforced by
  -- nothing. Portable across SQLite and Postgres (DB-SCHEMA-CONCEPT §1) — a plain column CHECK.
  CHECK (credits_used >= 0)
);

-- SEC-1: the SAME additive counter as \`usage\`, bucketed by a SHORT window instead of a UTC day.
--
-- The daily cap is a damage ceiling, not a brake: nothing bounded the RATE, so a runaway agent loop
-- (the per-provider throttle sustains ~5 paid calls/second ≈ 50 credits/second) could spend a whole
-- day's authorized budget in under a minute. That is not an over-spend — the ceiling still held —
-- but it removes any chance for a human to notice and intervene, which for an operator is
-- indistinguishable from a leak.
--
-- A SEPARATE table rather than a \`bucket_width\` column on \`usage\`: the day counter must keep summing
-- a whole day, and overloading \`usage.day\` with two bucket widths would make every existing
-- SELECT ambiguous and require a migration. This is a plain additive \`CREATE TABLE IF NOT EXISTS\`
-- against the same \`providers\` registry — no migration of anything (DB-SCHEMA-CONCEPT §1: portable
-- types, epoch-ms UTC integers, app-side logic only).
--
-- Rows are disposable: the guard only ever reads the CURRENT window, so anything older is dead
-- weight kept solely for after-the-fact inspection. \`SqliteBudgetStore\` prunes them opportunistically.
--
-- \`calls_made\` is the SECOND denominator (Q-3). A credit-denominated gate — including the
-- credits-per-window one above — can never refuse a call that costs ZERO credits: \`used + 0 >
-- ceiling\` is false for the entire life of any bucket, under any cap. \`entity.labels\`' query tier
-- is exactly that, and each call still costs two real HTTPS round trips against the operator's own
-- vendor account plus a fresh cache row with an attacker-selectable key. Counting CALLS is the only
-- denominator that can see it.
--
-- Deliberately a COLUMN on the same row, not another table: same provider, same window, same
-- transaction, and one row read instead of two.
CREATE TABLE IF NOT EXISTS usage_window (
  provider     TEXT NOT NULL REFERENCES providers(id),
  window_start INTEGER NOT NULL,           -- epoch-ms UTC bucket start: floor(ts/width)*width
  credits_used INTEGER NOT NULL DEFAULT 0, -- ADDITIVE, same signed-delta discipline as usage
  calls_made   INTEGER NOT NULL DEFAULT 0, -- ADDITIVE and MONOTONIC — never refunded, see below
  updated_at   INTEGER NOT NULL,           -- epoch-ms UTC of the last write
  PRIMARY KEY (provider, window_start),
  CHECK (credits_used >= 0),
  CHECK (calls_made >= 0)
);

-- ══ T-014 (task 014-36) — the eight engine tables of data-model.md §4.5 ══════════════════════════
--
-- §4.4 item 1: the SQLite axis is its own additive migration, one per storage engine, with no data
-- moving between them. One declaration serves BOTH profiles that use this axis — \`local\` and
-- \`network-sqlite\` — because the axis, not the transport, decides where state lives.
--
-- **Why identity tables are declared here at all, when stdio never fills them.** One DDL string and
-- one store implementation serve both dialects (§4.5.1), so a test of token revocation or of the
-- append-only audit log runs against SQLite — with no Postgres process in CI, which R-21 forbids
-- reaching over the network for. Absent this declaration those tests would have no offline home.
--
-- **A token row written by an stdio process is inert.** The stdio transport requires no token and
-- checks none, so an operator must not read such a row as protecting anything (§4.5.1).
--
-- **Why \`NOT NULL\` is spelled beside every \`TEXT PRIMARY KEY\`** (§4.5.2a): SQLite admits NULL in
-- such a column and Postgres does not, so the identical declaration would yield a different
-- constraint per axis — and a conformance test counting declared NOT NULL columns would find one
-- fewer here than in migration 002 for the same table.

CREATE TABLE IF NOT EXISTS users (
  id           TEXT PRIMARY KEY NOT NULL,   -- ULID, app-generated (§1.3)
  email        TEXT NOT NULL,               -- lower-cased by the writer: neither engine folds case
  display_name TEXT,
  role         TEXT NOT NULL,               -- 'admin' | 'user'   (R-15.3)
  status       TEXT NOT NULL,               -- 'active' | 'suspended'
  created_at   INTEGER NOT NULL,            -- epoch-ms UTC
  updated_at   INTEGER NOT NULL,
  UNIQUE (email),
  CHECK (role IN ('admin','user')),
  CHECK (status IN ('active','suspended'))
);

CREATE TABLE IF NOT EXISTS access_profiles (
  id                    TEXT PRIMARY KEY NOT NULL,   -- ULID
  name                  TEXT NOT NULL,
  status                TEXT NOT NULL,               -- 'active' | 'retired'
  credits_mode          TEXT NOT NULL,               -- 'unlimited' | 'metered'
  credits_balance_raw   TEXT,                        -- exact value as a string (§1.7)
  rate_limit_mode       TEXT NOT NULL,               -- 'unlimited' | 'metered'
  rate_limit_per_min    INTEGER,
  tool_allowlist_mode   TEXT NOT NULL,               -- 'all' | 'list'
  tool_allowlist_json   TEXT,                        -- JSON array as TEXT (§1.4)
  route_disclosure_mode TEXT NOT NULL DEFAULT 'full',-- 'full' | 'none'   (R-20.4)
  created_at            INTEGER NOT NULL,
  updated_at            INTEGER NOT NULL,
  UNIQUE (name),
  CHECK (status IN ('active','retired')),
  CHECK (credits_mode IN ('unlimited','metered')),
  CHECK (rate_limit_mode IN ('unlimited','metered')),
  CHECK (tool_allowlist_mode IN ('all','list')),
  CHECK (route_disclosure_mode IN ('full','none')),
  -- A mode and its value are declared together: a NULL that means "unlimited" cannot be told apart
  -- from a profile that was never provisioned — the L-10 class of defect (§7.5.3a).
  CHECK ((credits_mode = 'metered') = (credits_balance_raw IS NOT NULL)),
  CHECK ((rate_limit_mode = 'metered') = (rate_limit_per_min IS NOT NULL)),
  CHECK ((tool_allowlist_mode = 'list') = (tool_allowlist_json IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS api_tokens (
  id                TEXT PRIMARY KEY NOT NULL,   -- ULID
  user_id           TEXT NOT NULL REFERENCES users(id),
  access_profile_id TEXT NOT NULL REFERENCES access_profiles(id),
  token_hash        TEXT NOT NULL,               -- sha256(pepper || presented), lowercase hex
  prefix            TEXT NOT NULL,               -- identifies a token without disclosing it (R-15.2)
  name              TEXT,
  status            TEXT NOT NULL,               -- 'active' | 'revoked'
  expires_at        INTEGER,                     -- epoch-ms UTC; NULL = no expiry
  revoked_at        INTEGER,
  created_at        INTEGER NOT NULL,
  UNIQUE (token_hash),
  UNIQUE (prefix),
  CHECK (length(token_hash) = 64),
  CHECK (length(prefix) >= 8),
  CHECK (status IN ('active','revoked')),
  CHECK ((status = 'revoked') = (revoked_at IS NOT NULL)),
  CHECK (expires_at IS NULL OR expires_at > created_at)
);
CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens (user_id);

CREATE TABLE IF NOT EXISTS access_audit (
  id            TEXT PRIMARY KEY NOT NULL,   -- ULID; time-sortable, so the log reads in order
  ts            INTEGER NOT NULL,
  actor_user_id TEXT REFERENCES users(id),
  action        TEXT NOT NULL,
  target_type   TEXT NOT NULL,
  target_id     TEXT NOT NULL,
  before_json   TEXT,                        -- carries neither a token value nor its digest
  after_json    TEXT,
  created_at    INTEGER NOT NULL,
  CHECK (target_type IN ('user','api_token','access_profile'))
);
CREATE INDEX IF NOT EXISTS idx_access_audit_actor  ON access_audit (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_access_audit_target ON access_audit (target_id);
CREATE INDEX IF NOT EXISTS idx_access_audit_ts     ON access_audit (ts);

-- Append-only guard (§4.5.5). Postgres uses a rule plus a trigger; SQLite has no rules, so both
-- halves are BEFORE triggers. Removing the guard changes no column, which is what keeps the engine
-- move mechanical.
CREATE TRIGGER IF NOT EXISTS access_audit_no_update
  BEFORE UPDATE ON access_audit
BEGIN
  SELECT RAISE(ABORT, 'access_audit is append-only (data-model.md 4.5.5)');
END;
CREATE TRIGGER IF NOT EXISTS access_audit_no_delete
  BEFORE DELETE ON access_audit
BEGIN
  SELECT RAISE(ABORT, 'access_audit is append-only (data-model.md 4.5.5)');
END;

-- The limiter's cross-process state (R-7.1). \`providers\` is declared far above, and that order is
-- a condition: without it every limiter write is a foreign-key refusal, and R-7.7 degrades the
-- process to an in-process bucket permanently (§4.5.6).
CREATE TABLE IF NOT EXISTS provider_buckets (
  provider       TEXT NOT NULL REFERENCES providers(id),
  scope_key      TEXT NOT NULL DEFAULT '',   -- '' = one bucket per provider (R-7.4)
  tokens         REAL NOT NULL,              -- may be negative: the backlog the next caller waits out
  last_refill_ms INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL,
  PRIMARY KEY (provider, scope_key)
);

CREATE TABLE IF NOT EXISTS request_trace (
  id                  TEXT PRIMARY KEY NOT NULL,   -- ULID
  received_at         INTEGER NOT NULL,   -- pinned at admission (R-27.5)
  completed_at        INTEGER NOT NULL,
  principal_id        TEXT NOT NULL,      -- api_tokens.id, or 'local' in the local profile
  user_id             TEXT,
  access_profile_id   TEXT,
  client_request_id   TEXT NOT NULL,
  session_id          TEXT,
  transport           TEXT NOT NULL,      -- 'stdio' | 'http'
  tool                TEXT NOT NULL,
  capability          TEXT,               -- NULL in the two cases §4.5.7a names
  args_hash           TEXT,
  outcome             TEXT NOT NULL,      -- 'answer' | 'refusal' | 'partial_deadline'
  refusal_class       TEXT,
  served_from         TEXT NOT NULL,      -- 'cache' | 'coalesced' | 'vendor' | 'none'
  cache_age_ms        INTEGER,
  vendor_provider     TEXT REFERENCES providers(id),
  vendor_credits      INTEGER,            -- the vendor link is a COORDINATE, not a row reference:
  vendor_calls        INTEGER,            -- usage and usage_window are bucketed counters, so there
  vendor_day          INTEGER,            -- is no per-call row to point at (§4.5.7)
  vendor_window_start INTEGER,
  escalated_to_paid   INTEGER NOT NULL DEFAULT 0,  -- 0 | 1 (R-28.2)
  tried_json          TEXT,               -- operator-side data; never the client rendering
  created_at          INTEGER NOT NULL,
  -- Every component is NOT NULL on purpose: a NULL would switch the dedup off entirely (§4.5.7).
  UNIQUE (principal_id, client_request_id, received_at),
  CHECK (outcome IN ('answer','refusal','partial_deadline')),
  CHECK (served_from IN ('cache','coalesced','vendor','none')),
  CHECK ((outcome = 'refusal') = (refusal_class IS NOT NULL)),
  CHECK (escalated_to_paid IN (0,1))
);
CREATE INDEX IF NOT EXISTS idx_request_trace_principal ON request_trace (principal_id, received_at);
CREATE INDEX IF NOT EXISTS idx_request_trace_received  ON request_trace (received_at);
CREATE INDEX IF NOT EXISTS idx_request_trace_spend     ON request_trace (vendor_provider, vendor_day);

CREATE TABLE IF NOT EXISTS diagnostics (
  id           TEXT PRIMARY KEY NOT NULL,   -- ULID; also the identifier a withheld refusal carries
  ts           INTEGER NOT NULL,
  severity     TEXT NOT NULL,      -- 'info' | 'warn' | 'error'
  event        TEXT NOT NULL,      -- closed vocabulary of eight (§4.5.8)
  principal_id TEXT,               -- NULL when the request was refused before a principal existed
  session_id   TEXT,
  provider     TEXT,
  capability   TEXT,
  -- Deliberately WITHOUT REFERENCES: a diagnostics row is written mid-request and a trace row once,
  -- at completion. Under PRAGMA foreign_keys=ON a reference would refuse the mid-request insert,
  -- and the process would lose exactly the diagnostics it needs most (§4.5.8).
  trace_id     TEXT,
  detail_json  TEXT NOT NULL,      -- the FULL operator rendering (R-31.1)
  created_at   INTEGER NOT NULL,
  CHECK (severity IN ('info','warn','error'))
);
CREATE INDEX IF NOT EXISTS idx_diagnostics_ts       ON diagnostics (ts);
CREATE INDEX IF NOT EXISTS idx_diagnostics_event_ts ON diagnostics (event, ts);

CREATE TABLE IF NOT EXISTS retention_runs (
  id            TEXT PRIMARY KEY NOT NULL,   -- ULID
  job           TEXT NOT NULL,      -- the three named jobs of deployment.md §10.6
  target_table  TEXT NOT NULL,
  period_from   INTEGER NOT NULL,   -- inclusive
  period_to     INTEGER NOT NULL,   -- exclusive
  rows_affected INTEGER NOT NULL,   -- a pass that deleted zero rows still writes its row: "nothing
  started_at    INTEGER NOT NULL,   -- to delete" and "the job did not run" are different facts
  finished_at   INTEGER NOT NULL,
  outcome       TEXT NOT NULL,      -- 'ok' | 'failed'
  detail_json   TEXT,
  UNIQUE (job, period_from, period_to, started_at),
  CHECK (outcome IN ('ok','failed')),
  CHECK (period_to > period_from),
  CHECK (rows_affected >= 0)
);
CREATE INDEX IF NOT EXISTS idx_retention_runs_job ON retention_runs (job, started_at);

-- The phase 0 access profile. The id is a LITERAL, identical to the one migration 002 seeds: two
-- engines seeding independently would mint two ids for one entity, and a token's access_profile_id
-- would resolve on one host and dangle on the other (§4.5.3).
INSERT INTO access_profiles (
  id, name, status,
  credits_mode, credits_balance_raw,
  rate_limit_mode, rate_limit_per_min,
  tool_allowlist_mode, tool_allowlist_json,
  route_disclosure_mode,
  created_at, updated_at
) VALUES (
  '01JPHASE00000000000000000A', 'phase0-unlimited', 'active',
  'unlimited', NULL,
  'unlimited', NULL,
  'all', NULL,
  'full',
  0, 0
) ON CONFLICT (name) DO NOTHING;
`;

/**
 * Additive column migrations for `usage_window` (Q-3).
 *
 * `CREATE TABLE IF NOT EXISTS` is a no-op on a file that already has the table, so a column added
 * after the table shipped needs an explicit `ALTER`. SQLite has no `ADD COLUMN IF NOT EXISTS`, so
 * the store checks `PRAGMA table_info` first — which is what makes this idempotent, and what makes
 * the migration MECHANICAL rather than a project (DB-SCHEMA-CONCEPT §1: portable types, additive
 * shape, nothing engine-specific). `DEFAULT 0` means existing rows are correct without a backfill:
 * a window row that predates the column has, by definition, no counted calls, and every window row
 * is discarded within the hour anyway.
 */
export const USAGE_WINDOW_COLUMNS: readonly { name: string; ddl: string }[] = [
  {
    name: 'calls_made',
    ddl: 'ALTER TABLE usage_window ADD COLUMN calls_made INTEGER NOT NULL DEFAULT 0',
  },
];
