/**
 * DDL for the cache database (`${DATA_DIR}/cache.sqlite3`, ARCHITECTURE.md §3.2/§4.2), applied via
 * `db.exec(CACHE_DDL)` on every `SqliteCacheStore` open (idempotent — `IF NOT EXISTS` guards). This
 * is declarative data, not logic (task 003-3 note) — the same string ships unchanged from Phase 1.
 *
 * DB-SCHEMA-CONCEPT §1 portable-type discipline, applied to this NEW context (a cache, not the
 * analytics snapshot schema n8n writes independently):
 * - Only TEXT / INTEGER / REAL columns — no engine-specific column types anywhere in this schema.
 * - All time values are epoch-ms UTC INTEGER columns (`created_at`, `expires_at`) — never a native
 *   date/time column type and never a SQL date/time function in application logic.
 * - `cache_entries.id` is an app-generated ULID (TEXT) — the app always supplies it explicitly on
 *   insert; nothing here relies on the engine's own row-numbering feature, so IDs stay globally
 *   unique and portable across any future engine swap.
 * - `value_json` is the canonical result, JSON-serialized to TEXT — parsed app-side only, never
 *   queried with an engine-specific JSON operator.
 *
 * Write semantics: `cache_entries` is a recomputable projection, not an append-only observation log
 * (DB-SCHEMA-CONCEPT §1.5's "aggregates" branch, applied here) — `SqliteCacheStore.set()` uses
 * `INSERT ... ON CONFLICT (provider, capability, args_hash) DO UPDATE`, never a
 * conflict-do-nothing insert, so a re-fetched value always overwrites a stale row instead of
 * silently pinning it in place.
 *
 * `providers` is upserted from ALL 9 `adapterRegistrations` (including `pg-history`) BEFORE any
 * `cache_entries` row can reference it — `cache_entries.provider` is a foreign key into this table,
 * enforced only because `SqliteCacheStore` issues the explicit pragma below on every connection
 * open (DB-SCHEMA-CONCEPT §1.6 — the engine does not enforce a reference column by default).
 *
 * Forward-compatibility note (R-14 acceptance): a future M2 `usage(provider, day, credits_used)`
 * credit-budget table would reference this SAME `providers` registry as its own foreign key — this
 * cache DDL is designed so that table can be added later with a plain `CREATE TABLE`, no migration
 * of `providers`/`cache_entries` required. That `usage` table itself is explicitly OUT of this
 * task's scope (guard R-27) — not created here.
 */
export const CACHE_DDL = `
CREATE TABLE IF NOT EXISTS providers (
  id    TEXT PRIMARY KEY,   -- adapter.id, e.g. 'coingecko' | 'rpc-evm' | ... (ARCHITECTURE.md §3.2)
  kind  TEXT NOT NULL,      -- 'free' | 'paid' — informational only, reflects D4 priority
  notes TEXT
);

CREATE TABLE IF NOT EXISTS cache_entries (
  id          TEXT PRIMARY KEY,              -- ULID, generated by the app (DB-SCHEMA-CONCEPT §1.3)
  provider    TEXT NOT NULL REFERENCES providers(id),
  capability  TEXT NOT NULL,
  args_hash   TEXT NOT NULL,                 -- sha256(hex) of normalized args — NEVER secrets (§7.2)
  value_json  TEXT NOT NULL,                 -- canonical result, JSON as TEXT (DB-SCHEMA-CONCEPT §1.4)
  created_at  INTEGER NOT NULL,              -- epoch-ms UTC
  expires_at  INTEGER NOT NULL,              -- epoch-ms UTC = created_at + TTL(capability)
  UNIQUE (provider, capability, args_hash)
);

CREATE INDEX IF NOT EXISTS idx_cache_entries_expiry ON cache_entries (expires_at);
`;
