// GENERATED by scripts/gen-nansen-coverage.ts from the committed
// docs/onchain-analytics/raw/nansen-openapi-2026-07-23.json — do not edit by hand.
//
// Nansen's chain coverage differs PER CAPABILITY, and a COMPOSITE capability is covered only where
// EVERY sub-call it makes is covered — an intersection, never a union. The union would add chains
// on which the call half-succeeds after its credits are already spent (TASK-006 task 006-9, R-58).
//
// Values are NANSEN's own chain tokens, not our slugs; `registry.data.json`'s `vendors.nansen`
// column maps between them.

/** capability → the Nansen chain tokens on which it is covered. */
export const NANSEN_CHAIN_COVERAGE: Readonly<Record<string, readonly string[]>> = {
  // SmartMoneyChain ∩ TGMHoldersChain — 17 ∩ 25 = 17
  'smart-money.flows': [
    'arbitrum',
    'avalanche',
    'base',
    'bnb',
    'ethereum',
    'hyperevm',
    'iotaevm',
    'linea',
    'mantle',
    'monad',
    'optimism',
    'plasma',
    'polygon',
    'robinhood',
    'sei',
    'solana',
    'sonic',
  ],
  // TGMChain — 25 = 25
  'token.risk': [
    'arbitrum',
    'avalanche',
    'base',
    'bnb',
    'ethereum',
    'hyperevm',
    'hyperliquid',
    'injective',
    'iotaevm',
    'linea',
    'mantle',
    'mantra',
    'monad',
    'near',
    'optimism',
    'plasma',
    'polygon',
    'robinhood',
    'sei',
    'solana',
    'sonic',
    'starknet',
    'sui',
    'ton',
    'tron',
  ],
  // TGMHoldersChain — 25 = 25
  'entity.labels': [
    'arbitrum',
    'avalanche',
    'base',
    'bitcoin',
    'bnb',
    'ethereum',
    'hyperevm',
    'injective',
    'iotaevm',
    'linea',
    'mantle',
    'mantra',
    'monad',
    'near',
    'optimism',
    'plasma',
    'polygon',
    'robinhood',
    'sei',
    'solana',
    'sonic',
    'starknet',
    'sui',
    'ton',
    'tron',
  ],
};

/** The opt-in exhaustive `entity.labels` tier (`/profiler/address/labels`), narrower than the
 * default tier — listed separately so a caller can be refused BEFORE the 100cr escalation. */
export const NANSEN_EXHAUSTIVE_LABELS_CHAINS: readonly string[] = [
  'arbitrum',
  'avalanche',
  'base',
  'bnb',
  'ethereum',
  'hyperevm',
  'hyperliquid',
  'iotaevm',
  'linea',
  'mantle',
  'monad',
  'optimism',
  'plasma',
  'polygon',
  'robinhood',
  'sei',
  'solana',
  'sonic',
  'tron',
];
