// GENERATED by packages/core/scripts/generate-nansen-cost-table.mjs — DO NOT EDIT BY HAND.
// Source: docs/onchain-analytics/raw/nansen-openapi-2026-07-23.json's per-operation
// `x-credit-cost` (+ `x-credit-cost-variants`, below) extensions (system-architecture.md §3.2
// "Cost-table generation", task 005-3). Re-run
// `node packages/core/scripts/generate-nansen-cost-table.mjs` after a vendor spec refresh — a bare
// re-run is byte-idempotent (no `prettier --write` needed), so the diff IS the vendor price-drift
// signal (a committed, git-diff'able literal, never a runtime JSON parse of the 630KB spec).

/**
 * `(method+path) -> {free, pro}` credit cost. Exactly the ~8 endpoints M2's three capabilities
 * (`smart-money.flows`, `entity.labels`, `token.risk`) actually call — NOT all 74 operations in
 * the spec (out of scope, TASK.md §4). `costOf()` (cost-of.ts) looks keys up here; a key absent
 * from this table (future capability/endpoint drift) MUST resolve to
 * `Number.POSITIVE_INFINITY`, never `0` — fail-closed, R-37 MIN-3.
 */
export const NANSEN_COST_TABLE: Readonly<Record<string, { free: number; pro: number }>> = {
  'GET /api/v1/account': { free: 0, pro: 0 },
  'POST /api/v1/smart-money/netflow': { free: 5, pro: 5 },
  'POST /api/v1/tgm/holders': { free: 5, pro: 5 },
  'POST /api/v1/search/general': { free: 0, pro: 0 },
  'POST /api/v1/search/entity-name': { free: 0, pro: 0 },
  'POST /api/v1/profiler/address/labels': { free: 100, pro: 100 },
  'POST /api/v1/tgm/indicators': { free: 5, pro: 5 },
  'POST /api/v1/tgm/token-information': { free: 1, pro: 1 },
};

/**
 * Flat per-call surcharge (credits) when a request sets `premium_labels: true` on
 * `POST /api/v1/tgm/holders` — sourced from the SAME committed spec's
 * `x-credit-cost-variants['premium_labels=true']` extension on that operation
 * (the spec states ONLY a `pro` price for this variant; `cost-of.ts` applies it to BOTH plans
 * conservatively — see that file's own docstring for why). Regenerated here, not hand-maintained
 * (code review round 2 fix), so a future vendor change to this surcharge shows up as an ordinary
 * diff on THIS file instead of staying silently stale in `cost-of.ts`.
 */
export const NANSEN_PREMIUM_LABELS_COST = 150;
