// GENERATED by scripts/gen-blockscout-chains.ts from the committed
// docs/onchain-analytics/raw/blockscout-chains-2026-07-28.json — do not edit by hand.
//
// The numeric EVM chain ids Blockscout serves on its MAINNET explorers, taken from the vendor's own
// get_chains_list (100 rows: 47 testnets dropped, 53 kept).
//
// Keyed on chain_id, never on the vendor's `ecosystem` field — that field looks like a chain family
// and is not one (`ecosystem: "Solana"` is Neon, an EVM chain; `"Bitcoin/BCH"` is Rootstock, an EVM
// sidechain). Our registry maps these ids through `caip2 === \`eip155:\${id}\``.

export const BLOCKSCOUT_CHAIN_IDS: readonly number[] = [
  1, 10, 30, 61, 100, 109, 122, 130, 137, 148, 177, 239, 314, 324, 360, 480, 484, 488, 592, 698,
  714, 747, 869, 1135, 1514, 1729, 1829, 1868, 1890, 2288, 2366, 4326, 4663, 6497, 7000, 8021, 8453,
  8822, 13371, 32769, 34443, 41923, 42161, 42170, 42220, 42793, 57073, 73115, 102030, 534352,
  612055, 685689, 245022934,
];
